config/routes.rb
Knowledge::Application.routes.draw do
############## comente el get articles new y puse el resources articles
#  get "articles/new"
  root to: redirect("/#{I18n.default_locale}/")

  scope ':locale', locale: /#{I18n.available_locales.join('|')}/ do
    #[es, en, fr] => /es|en|fr/
    root to: 'articles#index'

    resources :articles do
      member do
        get 'filter'
      end
    end
    
    match '*dummy', to: 'error#error_404'
  end

#get "articles/show"

#match '/edit',  to: 'articles#edit'

  match '*dummy', to: 'error#error_404', locale: I18n.default_locale.to_s

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :content, :title
  validates :title, :content, presence: true
  validates :title, length: { maximum: 50 }
  has_and_belongs_to_many :tags
  translates :title, :content

  def self.search(search)
    if search
      find(:all, :conditions => ['title LIKE ? or content LIKE ? ', "%#{search}%", "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  validates :name, presence: true, length: { maximum: 63 }
  has_and_belongs_to_many :articles
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale

  protected
  def set_locale
    params[:locale] ||= I18n.default_locale
    I18n.locale = params[:locale]
  end
  
  def default_url_options(options={})
    {locale: I18n.locale }
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
   @field = params[:order_by] || 'id'
   @direction = params[:direction].try(:upcase) == 'ASC' ? 'ASC' : 'DESC'
   @articles = Article.paginate(page: params[:page], order: "#{@field} #{@direction}").search(params[:search])
 #  @articles = Article.search(params[:search])
  end
  def new
    @article = Article.new
    @tags = []
  end
  def show
    id = params[:id]
    @article = Article.find(id)
    @tags = @article.tags
  end
  def edit
    @article = Article.find(params[:id])
    @tags = @article.tags.map(&:name).join(' ')
  end  
  def update
    @article = Article.find params[:id]
    tag_names = params[:tags].split(' ').uniq
    form_tags = tag_names.map {|tag| Tag.find_or_create_by_name(tag)}
    article_tags = @article.tags
    new_tags = form_tags - article_tags
    old_tags = article_tags - form_tags
    new_tags.each do |tag|
      @article.tags << tag
    end
    old_tags.each do |tag|
      @article.tags.destroy(tag)
    end
    @tag = @article.tags.map(&:name).join(' ')
    if @article.update_attributes(params[:article])    
      flash[:notice] = t(:success_update_flash) 
      redirect_to article_path(@article)
    else
      flash[:error] = t(:error_saving_flash)
      render :edit
    end
  end  
  def create
    @article = Article.new(params[:article])
    if @article.save    
      tag_names = params[:tags].split(' ').uniq
      tag_names.each do |tag|
        @article.tags << Tag.find_or_create_by_name(tag)
      end
      flash[:notice] = t(:success_create_flash)
      redirect_to article_path(@article)
    else
      flash[:error] = t(:error_saving_flash)
      render :new
    end
  end
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:notice] = t(:success_destroy_flash)
    redirect_to articles_url
  end
  def filter
    @tag = Tag.find_by_name(params[:id])
    @articles = @tag.articles
  end
end

app/controllers/error_controller.rb
class ErrorController < ApplicationController
  def error_404
    render status: 404, text: 'error 404'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def index_table_header name, field, current_field, current_direction
    if current_field == field.to_s and current_direction == 'DESC'
      direction = 'ASC'
      displayed_name = "#{image_tag 'arriba.jpg' } #{name}"
    else
      direction = 'DESC'
      displayed_name = "#{image_tag 'abajo.jpg' } #{name}"
    end
    link_to displayed_name.html_safe, articles_path(order_by: field, direction: direction) 
  end
end

app/helpers/error_helper.rb
module ErrorHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for @article do |f| %>
  <%= f.input :title %>
  <%= f.input :content, :as => :text %>
  <%= text_field_tag :tags, @tags %> 
  <%= f.button :submit %>
<% end %>

app/views/articles/_searcher.html.erb
<%= form_tag articles_path, :method => 'get' do %>
  <div>
    <%= text_field_tag :search, params[:search] %>
    
    <%= submit_tag t('articles.search'), :name => nil %>
  </div> 
<%end%>
  

app/views/articles/edit.html.erb
<% provide(:title, t('articles.edit.title')) %>

<h1><%= t 'articles.edit.content' %></h1>

<div class="row">
  <div class="edit-form">
    <%= render 'form' %>
    <%= link_to t('articles.edit.back'), @article %>
    <%= button_to t('articles.delete'), @article, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
 </div>
</div>

app/views/articles/filter.html.erb
<% provide :title, @tag.name %>
<h1><%= @tag.name %></h1>
<%= link_to t('articles.new.back'), articles_path %>
<table>
  <thead>
    <tr>
      <th> <%=  index_table_header t('articles.index.title_table'), :title, @field, @direction %> </th>
    </tr>
  </thead>
  <tbody>
    <li>        
      <% @articles.each do |article| %>
        <tr>
          <td>
            <%= link_to article.title, article_path(article) %>
          </td
        </tr>
      <% end %>
    </li>
  </tbody>
</table>
<div id="back-list">
<%= link_to t('articles.new.back'), articles_path %>
</div>

app/views/articles/index.html.erb
<% provide(:title, t('articles.index.title')) %>

<h1><%= t 'articles.index.content' %></h1>
<%= render 'searcher' %>
<%= link_to t('articles.index.new'), new_article_path %>  
<%= will_paginate %>
<table>
  <thead>
    <tr>
      <th> <%=  index_table_header t('articles.index.id_table'), :id, @field, @direction %> </th>    
      <th> <%=  index_table_header t('articles.index.title_table'), :title, @field, @direction %> </th>
      <th> <%=  index_table_header t('articles.index.release_table'), :title, @field, @direction %></th>
      <th> <%=  t('articles.index.info_table') %> </th>
    </tr>
  </thead>
  <tbody>  
    <li>        
    <% @articles.each do |article| %>
      <tr>
       <td>
         <%= link_to article.id, article_path(article) %>
       </td>
	     <td>
	       <%= link_to (article.title|| t('articles.untitled')), article_path(article) %>	       
    	 </td>
       <td>
         <%= time_ago_in_words(article.created_at) %>
       </td>	     
       <td>
          <% article.tags.each do |tag| %>
            <%= link_to tag.name, filter_article_path(tag.name) %>   
          <% end %>
       </td>       
      </tr>
    <% end %>
    </li>
  </tbody>  
</table>

<%= will_paginate %>

app/views/articles/new.html.erb
<% provide(:title, t('articles.new.title')) %>

<h1><%= t 'articles.new.content' %></h1>
<%= render 'form' %>

<%= link_to t('articles.new.back'), articles_path %>

app/views/articles/show.html.erb
<% provide(:title, t('articles.show.title')) %>

<h1><%= t 'articles.show.content' %></h1>
<h2><span id='title'><%= t 'articles.title' %>:</span> <%= (@article.title) %></h2>
<h3><%= t 'articles.content' %>: </h3>
<div id="contenido">
	<%= raw RedCloth.new(sanitize(@article.content) || "").to_html %>
	<div id="tag">
		<% if @tags.any? %>
		    <span id="contenido-tag">Tags:</span> <%= @tags.map(&:name).join(', ') %>
		    <br />
		<% end %>
	</div>
	<div id="publicacion">
	<%= t 'articles.released' %> <%= t(@article.created_at, format: :short) %>.
	</div>
</div>
<%= link_to t('articles.show.edit'), edit_article_path(@article) %>
<%= link_to t('articles.show.back'), articles_path %>
<%= button_to t('articles.delete'), @article, :method => :delete, :data => { :confirm => 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Knowledge Base - <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="flash">	
  <% flash.each do |type, message| %>
  <div id = "flash-<%= type.to_s %>"><%= message %></div>
  <% end %>
</div>
<div id="language">
	<% I18n.available_locales.each do |locale| %>
		<% if locale == I18n.locale %>
			<span id="current-language">
				<%= I18n.locale.to_s %>
			</span>
		<% else %>
			<%= link_to locale, url_for(locale: locale) %>
		<% end %>
	<% end %>
</div>	
<%= yield %>

</body>
</html>